### ISSUE TITLE
Documentation says 3 years, but it only waits 18 days

### ISSUE THREAD

**Issue by sighol** [TheZoq2/brexit#1]
First, thank you for a very useful create.

However, I believe it will wait just over 18 days, and not 3 years.
https://github.com/TheZoq2/brexit/blob/14e60dfa5d5ac578a9159e24d73df758a37a2b4f/src/lib.rs#L6

3 years is 60 * 60 * 24 * 365 * 3.

**Comment by TheZoq2** [comment]
Ah, of course, thanks for the report.

Fixed in the newly released 1.0.1 version
